p1/Controllers/ShowPurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using p1.Models;
using p1.ModelView;
using Newtonsoft.Json;
using p1.Repositories;
using System.Data.Entity;


namespace p1.ModelView
{
    public class ShowPurchaseController : Controller
    {
        // GET: ShowPurchase
        ProjectDBEntities context = new ProjectDBEntities();


        public ActionResult Index()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                var list = context.Purchases.ToList();
                return View(list);
            }
        }
        public ActionResult Approved()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef" )
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                var list = context.Purchases.ToList();
                return View(list);
            }
        }
        [HttpGet]
        [Route("ShowPurchase/Delete/{purchase_no?}")]

        public ActionResult Delete(string purchase_no)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                try
                {

                    var pd = context.Purchase_Detail.Where(x => x.purchase_no.Equals(purchase_no)).ToList();

                    foreach (var data in pd)
                    {
                        context.Purchase_Detail.Remove(data);
                        context.SaveChanges();

                    }
                    var purchase = context.Purchases.SingleOrDefault(x => x.purchase_no.Equals(purchase_no));
                    context.Purchases.Remove(purchase);
                    context.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch
                {
                    return View(nameof(DetailsPurchase), purchase_no);
                }
            }
        }
        public ActionResult DetailsPurchase(string purchase_no)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                if (purchase_no == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var editdata = context.Purchases.SingleOrDefault(x => x.purchase_no.Equals(purchase_no));
                if (editdata == null)
                {
                    return HttpNotFound();
                }
                int id = 0;
                List<ItemsViewModel> list = new List<ItemsViewModel>();
                var data_list = context.Purchase_Detail.Where(x => x.purchase_no.Equals(purchase_no)).ToList();
                foreach (var data_item in data_list)
                {
                    ItemsViewModel itemsView = new ItemsViewModel();
                    itemsView.id = id + 1;
                    itemsView.item_name = data_item.item_name;
                    itemsView.item_rate = data_item.item_rate;
                    itemsView.qty = data_item.qty;
                    itemsView.amount = data_item.item_rate * data_item.qty;
                    list.Add(itemsView);
                }

                var data = context.Purchases.Where(x => x.purchase_no.Equals(purchase_no)).SingleOrDefault();


                Detail detail = new Detail();
                detail.vendor_no = data.vendor_no;
                detail.invoice_no = data.invoice_no;
                detail.invoice_date = data.invoice_date;
                detail.purchase_no = purchase_no;
                detail.vendor_name = context.Vendor_Master.Where(x => x.vendor_code == data.vendor_no).Select(x => x.vendor_name).SingleOrDefault();
                detail.List = list;
                return View(detail);

            }


        }
        [HttpPost]
        public ActionResult UpdateStatusNew(int id)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                if (Request.IsAjaxRequest())
                {
                    Purchase purchase_to_update = context.Purchases.Where(x => x.id == id).SingleOrDefault();

                    purchase_to_update.status = "New";
                    purchase_to_update.invoice_date = null;
                    purchase_to_update.invoice_no = null;
                    purchase_to_update.tax = 0;
                    if (ModelState.IsValid)
                    {
                        context.Entry(purchase_to_update).State = EntityState.Modified;
                        var pd_list = context.Purchase_Detail.Where(x => x.purchase_no.
                        Equals(purchase_to_update.purchase_no)).ToList();
                        foreach (var data in pd_list)
                        {
                            Inventory inventory = context.Inventories.Where(x => x.item_code == data.item_code).SingleOrDefault();
                            inventory.current_qty = inventory.current_qty - data.qty;

                        }
                        context.SaveChanges();
                        return Json(string.Format("Invoice No:{0}", purchase_to_update.purchase_no));
                    }


                }
                {
                    return RedirectToAction("Index");
                }
            }
        }
        [HttpPost]
        public ActionResult Update(int id,long invoice_no,string invoice_date, long tax)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                if (Request.IsAjaxRequest())
                {
                    DateTime date = Convert.ToDateTime(invoice_date);
                    Purchase purchase_to_update = context.Purchases.Where(x => x.id == id).SingleOrDefault();
                    purchase_to_update.invoice_date = date;
                    purchase_to_update.invoice_no = invoice_no;
                    purchase_to_update.tax = tax;
                    purchase_to_update.status = "Approved";

                    if (ModelState.IsValid)
                    {
                        context.Entry(purchase_to_update).State = EntityState.Modified;
                        var pd_list = context.Purchase_Detail.Where(x => x.purchase_no.Equals(purchase_to_update.purchase_no)).ToList();
                        foreach (var data in pd_list)
                        {
                            Inventory inventory = context.Inventories.Where(x => x.item_code == data.item_code).SingleOrDefault();
                            inventory.current_qty = inventory.current_qty + data.qty;
                            context.SaveChanges();
                        }
                    }
                    context.SaveChanges();
                    return Json(string.Format("Invoice No:{0}", invoice_date));
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }

        
    }
}

p1/Views/ShowPurchase/Approved.cshtml
@model IEnumerable<p1.Models.Purchase>

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
   
}
<link href="~/Content/Custom.css" rel="stylesheet" />

<link href="~/Content/header.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<div class="card card-cyan">
    <div class="card card-header"><h3 class="card-title">Approved Purchase Order</h3></div>
    <div class="card-body">

        <table class="table">
            <tr>
                <th>
                    Purchase No
                </th>
                <th>
                    Order Date
                </th>

                <th>
                    Vendor
                </th>
                <th>
                    Invoice No
                </th>
                <th>Invoice Date</th>
                <th>
                    Status
                </th>
                <th>

                </th>

            </tr>

            @foreach (var item in Model)
            {

                if (item.status != "New")
                {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.purchase_no)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.order_date)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Vendor_Master.vendor_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.invoice_no)
            </td>
            <td>
                @Html.DisplayFor(modelItem=>item.invoice_date)
            </td>
            <td>
                @{
                    int data = item.id;
                }
                <input type="submit" class="btn btn-info id" value="New" id="@data" onclick="getid('@data')" />
            </td>
            <td>

            <td>
                @Html.ActionLink("Detail Of Order", "DetailsPurchase", new { purchase_no = item.purchase_no }, new { @class = "btn btn-info" })
            </td>
   

        </tr>
                }
            }

        </table>
    </div>
    <script>
        function getid(id) {
          
            $.ajax({
                type: "POST",
                url: "@Url.Action("UpdateStatusNew","ShowPurchase")",
                data: "{id:"+id+"}",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (response) {
                    location.reload();
                }
            });
        }
    </script>

p1/Views/ShowPurchase/DetailsPurchase.cshtml
@model p1.ModelView.Detail


@{

    Layout = "~/Views/Shared/_Layout.cshtml";
   
}
<style>



    label {
        margin-top: 20px;
    }
</style>

<link href="~/Content/Custom.css" rel="stylesheet" />
<link href="~/Content/font-awesome.css" rel="stylesheet" />
<link href="~/Content/font-awesome.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<link href="~/Content/header.css" rel="stylesheet" />
<div class="card card-cyan">
    <div class="card card-header"><h3 class="card-title">@Model.purchase_no Detail</h3></div>
    <div class="card-body">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.purchase_no)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.purchase_no)
            </dd>
            @if (Model.invoice_no != null)
            {
            <dt>
                @Html.DisplayNameFor(model => model.invoice_no)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.invoice_no)
            </dd>

            }
             @if (Model.invoice_date != null)
             {
            <dt>
                @Html.DisplayNameFor(model => model.invoice_date)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.invoice_date)
            </dd>
             }
            <dt>

                @Html.DisplayNameFor(model => model.vendor_no)

            </dt>
            <dd>
                @Html.DisplayFor(model => model.vendor_name)
            </dd>

            <div id="OrderItem">
                <table table class="table-condensed table" id="OrderTable" style="margin-left:20px;">
                    <tr>
                        <th>
                            Item
                        </th>
                        <th>
                            Rate
                        </th>
                        <th>
                            Qty
                        </th>
                        <th>
                            Amount
                        </th>

                    </tr>
                    @foreach (var item in Model.List)
                    {
                        <tr>
                            <td>
                                @item.item_name
                            </td>
                            <td>
                                @item.item_rate
                            </td>
                            <td>
                                @item.qty
                            </td>
                            <td>
                                @item.amount
                            </td>

                        </tr>
                    }
                    <tr>
                        <td>
                            <b>
                                Total
                            </b>
                        </td>
                        <td>
                        </td>
                        <td>
                        </td>
                        <td>
                            <b>
                                @Model.List.Sum(x => x.amount)
                            </b>
                        </td>

                    </tr>
                </table>

            </div>
        </dl>



        <div class="form-actions no-color">
            @Html.ActionLink("Cancel Order", "Delete", new { purchase_no = Model.purchase_no }, new { @class = "btn btn-danger" })



            |
            <input type="button" class="btn btn-info" value="Back" onclick="location.href='@Url.Action("Index","ShowPurchase")'" />
        </div>

    </div>

p1/Views/ShowPurchase/Index.cshtml
@model IEnumerable<p1.Models.Purchase>

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
 
}
<link href="~/Content/Custom.css" rel="stylesheet" />

<link href="~/Content/header.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-3.4.1.js"></script>
<div class="card card-cyan">
    <div class="card card-header"><h3 class="card-title">New Purchase Order</h3></div>
    <div class="card-body">

        <table class="table">
            <tr>
                <th>
                    Purchase No
                </th>
                <th>
                    Order Date
                </th>

                <th>
                    Vendor
                </th>
                <th>
                    Status
                </th>
                <th>

                </th>

            </tr>

            @foreach (var item in Model)
            {

                if (item.status == "New")
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.purchase_no)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.order_date)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Vendor_Master.vendor_name)
                        </td>

                        <td>
                            @{
                                int data = item.id;
                                var dataAll = "Purchase No:" + item.purchase_no + "<br>" + "Vendor:" + item.Vendor_Master.vendor_name;
                            }
                            <input type="submit" class="btn btn-info id" value="Approved" id="@data" onclick="getid('@data','@dataAll')" />
                        </td>
                        <td>
                            @Html.ActionLink("Detail Of Order", "DetailsPurchase", new { purchase_no = item.purchase_no }, new { @class = "btn btn-info" })
                        </td>
                    </tr>
                }
            }

        </table>
        <div class="modal fade" id="ApprovedDetail" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Details Invoice</h5>

                    </div>
                    <input type="hidden" id="purchase_id" />
                    <div class="modal-body" id="approve_data">
                        <p id="purchaseData" style="font-weight:bold;">

                        </p>
                        <form>
                            <div class="form-group">
                                <label for="invoice-no" class="col-form-label">Invoice No</label>
                                <input type="text" class="form-control" id="invoice-no" />
                                <span class="text-danger" id="invcoie_no"></span>
                            </div>

                            <div class="form-group">
                                <label for="invoice-date" class="col-form-label">Invoice Date</label>
                                <input type="date" class="form-control" id="invoice-date" />
                                <span class="text-danger" id="invcoie_date"></span>

                            </div>

                            <div class="form-group">
                                <label for="tax" class="col-form-label">Tax</label>
                                <input type="number" min="0" class="form-control" id="tax" />
                                <span class="text-danger" id="tax"></span>

                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" id="close_modal" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="change_status">Approve</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>
    <script>
    function getid(id, data) {
        $("#purchaseData").html(data);
        $("#purchase_id").val(id);
        $("#ApprovedDetail").modal();

    }
    $(document).ready(function () {

        $("#change_status").on('click', function () {
            var dateData = $("#invoice-date").val();
            var dataObject = {};
            dataObject.id = $("#purchase_id").val();
            dataObject.invoice_no = $("#invoice-no").val();
            dataObject.invoice_date = dateData.toString();
            dataObject.tax = $("#tax").val();
            $.ajax({
                type: "POST",
                url: "@Url.Action("Update","ShowPurchase")",
                data: JSON.stringify(dataObject),
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (response) {
               
                    location.reload();
                }
            });
        });
    });
    </script>