p1/Controllers/ItemController.cs
using p1.Models;
using p1.ModelView;
using p1.Repositories;
using System.Linq;
using System.Web.Mvc;
using System;
using p1.Repositories;
namespace p1.Controllers
{
    public class ItemController : Controller
    {
        // GET: Report
        ProjectDBEntities context = new ProjectDBEntities();
        public ActionResult Index()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                var list = context.Item_Master.Join(context.Inventories, x => x.item_code, y => y.item_code,
                  (x, y) => new InventoryRepo { item = x, inventory = y }).OrderBy(data=>data.item.item_name).ToList();
                //var list = context.Item_Master.Join(context.Inventories, x => x.item_code, y => y.item_code, (x, y) => new InventoryRepo { item = x, inventory = y }).ToList();
                return View(list);
            }
        }
        [Route("Item/Delete/{item_code}")]
        public ActionResult Delete(int item_code)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {

                TempData["role"] = Session["role"].ToString();
                Inventory inventory = context.Inventories.Where(x => x.item_code == item_code).SingleOrDefault();
                context.Inventories.Remove(inventory);
                Item_Master item = context.Item_Master.Where(x => x.item_code == item_code).SingleOrDefault();
                context.Item_Master.Remove(item);
                context.SaveChanges();


                return RedirectToAction("Index");
            }
        }
        [Route("Item/Increase/{item_code}")]
        public ActionResult Increase(int item_code)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {
                TempData["role"] = Session["role"].ToString();
                Inventory i = context.Inventories.Where(x => x.item_code == item_code).SingleOrDefault();
                i.current_qty = i.current_qty + 1;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

        [Route("Item/Decrease/{item_code}")]
        public ActionResult Decrease(int item_code)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {
                TempData["role"] = Session["role"].ToString();
                Inventory i = context.Inventories.Where(x => x.item_code == item_code).SingleOrDefault();
                i.current_qty = i.current_qty - 1;
                context.SaveChanges();

                return RedirectToAction("Index");
            }
        }

       public ActionResult Create()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {
                TempData["role"] = Session["role"].ToString();
                return View();
            }
        }
        [HttpPost]
        public ActionResult Create(InventoryRepo inventoryRepo)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {

                TempData["role"] = Session["role"].ToString();
                context.Item_Master.Add(inventoryRepo.item);
                context.SaveChanges();
                if (inventoryRepo.item.item_code > 0)
                {
                    inventoryRepo.inventory.item_code = inventoryRepo.item.item_code;
                    context.Inventories.Add(inventoryRepo.inventory);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
        }
        [Route("Item/Edit/{item_code}")]

        public ActionResult Edit(int item_code)
        {

            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }
            else if (Session["role"].ToString() == "Accountant")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }

            else
            {
                TempData["role"] = Session["role"].ToString();
                var item = context.Item_Master.SingleOrDefault(x => x.item_code == item_code);
                var inventory = context.Inventories.SingleOrDefault(x => x.item_code == item_code);
                InventoryRepo inventoryRepo = new InventoryRepo();
                inventoryRepo.item = item;
                inventoryRepo.inventory = inventory;
                return View(inventoryRepo);
            }
        }
        [HttpPost]
        public ActionResult Edit(InventoryRepo inventoryRepo)
        {
            var item_code = inventoryRepo.item.item_code;
            Item_Master item = context.Item_Master.SingleOrDefault(x => x.item_code == item_code);
            Inventory inventory= context.Inventories.SingleOrDefault(x => x.item_code == item_code);
            item.item_name = inventoryRepo.item.item_name;
            item.item_rate = inventoryRepo.item.item_rate;
            item.item_unit = inventoryRepo.item.item_unit;
            inventory.min_qty = inventoryRepo.inventory.min_qty;
            inventory.current_qty = inventoryRepo.inventory.current_qty;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    } 

}

p1/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using p1.Models;
using p1.Repositories;
using p1.ReportsModel;
using System.Data.Entity;

namespace p1.Controllers
{
    public class ReportController : Controller
    {
        ProjectDBEntities context = new ProjectDBEntities();
        // GET: Report
        public ActionResult Index()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }

            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                var restaurat_code = Convert.ToInt32(Session["restaurat_code"]);
                VendorRepo dropdown = new VendorRepo();
                Vendor_Tax vendor_Tax = new Vendor_Tax();
                vendor_Tax.vendors = dropdown.GetVendor();
                return View(vendor_Tax);
            }
        }


        [HttpGet]
        [Route("Report/GetDataTax/{vendorCode}/{startDate}/{endDate}")]
        public ActionResult GetDataTax(int vendorCode,string startDate,string endDate)
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }

            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                DateTime? _startDate;
                DateTime? _endDate;
                if (startDate == "")
                {
                    _startDate = null;
                }
                else
                {
                    _startDate = Convert.ToDateTime(startDate);
                }
                if (endDate == "")
                {
                    _endDate = null;
                }

                else
                {
                    _endDate = Convert.ToDateTime(endDate);
                }

                if (_startDate is null && _endDate is null)
                {
                    var vendor = context.Purchases.Where(x => x.vendor_no == vendorCode).Select(x => new { x.purchase_no,x.order_date,x.invoice_date, x.invoice_no, x.tax }).ToList();


                    if (vendor is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = vendor }, JsonRequestBehavior.AllowGet);

                    }
                }
                else if ((_startDate != null) && _endDate is null)
                {
                    var vendor = context.Purchases.Where(x => x.vendor_no == vendorCode && x.order_date >= _startDate).Select(x => new { x.purchase_no, x.order_date, x.invoice_date, x.invoice_no, x.tax }).ToList();

                    if (vendor is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = vendor }, JsonRequestBehavior.AllowGet);
                    }
                }

                else if ((_endDate != null) && _startDate is null)
                {
                    var vendor = context.Purchases.Where(x => x.vendor_no == vendorCode && x.order_date <= _endDate).Select(x => new { x.purchase_no, x.order_date, x.invoice_date, x.tax }).ToList();
                    if (vendor is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = vendor }, JsonRequestBehavior.AllowGet);
                    }
                }

                else if ((_endDate != null) && (_startDate != null))
                {
                    var vendor = context.Purchases.Where(x => x.vendor_no == vendorCode && x.order_date >= _startDate && x.order_date <= _endDate).Select(x => new { x.purchase_no, x.order_date,x.invoice_date, x.invoice_no, x.tax }).ToList();
                    if (vendor is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = vendor }, JsonRequestBehavior.AllowGet);
                    }

                }
            }
            return View();
        }

        public ActionResult ItemsReport()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }

            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();
                var restaurat_code = Convert.ToInt32(Session["restaurat_code"]);
                ItemRepo dropdown = new ItemRepo();
                ItemBase itemBase = new ItemBase();
                itemBase.items = dropdown.GetItemCode();
                return View(itemBase);
            }
        }
        [HttpGet]
        [Route("Report/GetDataItem/{itemCode}/{startDate}/{endDate}")]

        public ActionResult GetDataItem(int itemCode, string startDate, string endDate)
            {
                TempData["role"] = Session["role"].ToString();
                DateTime? _startDate;
                DateTime? _endDate;
                if (startDate == "")
                {
                    _startDate = null;
                }
                else
                {
                    _startDate = Convert.ToDateTime(startDate);
                }
                if (endDate == "")
                {
                    _endDate = null;
                }

                else
                {
                    _endDate = Convert.ToDateTime(endDate);
                }
                if (_startDate is null && _endDate is null)
                {




                    var items =
                    context.Purchase_Detail.Join(context.Purchases, pd => pd.purchase_no, p => p.purchase_no, (pd, p) => new { pd, p })
                    .Where(m => m.pd.item_code == itemCode)
                    .Select(m => new { m.p.purchase_no, m.p.order_date, m.pd.item_rate, m.pd.qty, m.pd.amount }).ToList();
                    if (items is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = items }, JsonRequestBehavior.AllowGet);

                    }
                }

                else if ((_startDate != null) && _endDate is null)
                {
                    var items =
                    context.Purchase_Detail.Join(context.Purchases, pd => pd.purchase_no, p => p.purchase_no, (pd, p) => new { pd, p })
                    .Where(m => m.pd.item_code == itemCode && m.p.order_date >= _startDate)
                    .Select(m => new { m.p.purchase_no, m.p.order_date, m.pd.item_rate, m.pd.qty, m.pd.amount }).ToList();

                    if (items is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = items }, JsonRequestBehavior.AllowGet);
                    }
                }

                else if ((_endDate != null) && _startDate is null)
                {
                    var items =
                    context.Purchase_Detail.Join(context.Purchases, pd => pd.purchase_no, p => p.purchase_no, (pd, p) => new { pd, p })
                    .Where(m => m.pd.item_code == itemCode && m.p.order_date <= _endDate)
                    .Select(m => new { m.p.purchase_no, m.p.order_date, m.pd.item_rate, m.pd.qty, m.pd.amount }).ToList();

                    if (items is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = items }, JsonRequestBehavior.AllowGet);
                    }
                }

                else if ((_endDate != null) && (_startDate != null))
                {
                    var items =
                    context.Purchase_Detail.Join(context.Purchases, pd => pd.purchase_no, p => p.purchase_no, (pd, p) => new { pd, p })
                    .Where(m => m.pd.item_code == itemCode && m.p.order_date >= _startDate && m.p.order_date < _endDate)
                    .Select(m => new { m.p.purchase_no, m.p.order_date, m.pd.item_rate, m.pd.qty, m.pd.amount }).ToList();

                    if (items is null)
                    {
                        return Json(null);
                    }
                    else
                    {
                        return Json(new { data = items }, JsonRequestBehavior.AllowGet);
                    }
                }



                return View();
            }
        public ActionResult StatusReport()
        {
            if (Session["role"] == null)
            {
                return RedirectToAction("Login", "Account");

            }

            else if (Session["role"].ToString() == "Chef")
            {
                TempData["role"] = Session["role"].ToString();
                return RedirectToAction("Index", "Roles");
            }
            else
            {
                TempData["role"] = Session["role"].ToString();

                return View();
            }
        }

p1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase</title>

    @Scripts.Render("~/bundles/modernizr")
    <style>
        .outer {
            display: table;
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
        }

        .middle {
            display: table-cell;
            vertical-align: middle;
        }

        .inner {
            margin-left: auto;
            margin-right: auto;
            width: 400px;
            /*whatever width you want*/
        }

        body, .content-wrapper {
            padding-top: 0px !important;
            background-color: #e6f2ff !important;
        }

        .nav-pills .nav-link {
            color: #c2c7d0 !important;
        }
    </style>

    <link href="~/Content/DataTables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="~/Content/DataTables/css/buttons.bootstrap4.min.css" rel="stylesheet" />



    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
   \
    <div class="wrapper">
        <aside class="main-sidebar sidebar-dark-primary elevation-4">

            <a href="https://www.gatisofttech.com/" class="brand-link">

                <span class="brand-text font-weight-light">Gati</span>
            </a>

            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                    with font-awesome or any other icon font library -->
                    @if (TempData["role"].ToString() != "Chef")
                    {
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-money-check"></i>
                                <p>
                                    Purchase
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">

                                @if (TempData["role"].ToString() == "Accountant")
                                {


                                    <li class="nav-item">
                                        <a href="@Url.Action("Index", "Purchase")" class="nav-link">
                                            <i class="fas fa-cart-plus"></i>
                                            <p>Entry</p>

                                        </a>
                                    </li>
                                }
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "ShowPurchase")" class="nav-link">
                                        <i class="fas fa-list-alt"></i>
                                        <p>Show(New)</p>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="@Url.Action("Approved", "ShowPurchase")" class="nav-link">

                                        <i class="fa fa-check-circle"></i>
                                        <p>Show(Approved)</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    }
                    @if (TempData["role"].ToString() == "Manager")
                    {
                        <li class="nav-item" style="color: #c2c7d0!important;">
                            <a href="@Url.Action("Index", "Vendor")" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>
                                    Vendors
                                </p>
                            </a>
                        </li>
                    }
                    @if (TempData["role"].ToString() == "Manager" || TempData["role"].ToString() == "Chef")
                    {
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Item")" class="nav-link">
                                <i class="nav-icon fas fa-shopping-bag"></i>
                                <p>
                                    Item
                                </p>
                            </a>
                        </li>
                    }

                    @if (TempData["role"].ToString() != "Chef")
                    {
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-list-alt"></i>
                                <p>
                                    Reoprts
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="@Url.Action("Index", "Report")" class="nav-link">
                                        <i class="fas fa-cart-plus"></i>
                                        <p>Vendor Tax</p>

                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("ItemsReport", "Report")" class="nav-link">
                                        <i class="fas fa-cart-plus"></i>
                                        <p>Item Report</p>

                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("StatusReport", "Report")" class="nav-link">
                                        <i class="fas fa-battery-half"></i>
                                        <p>Status Report</p>
                                    </a>
                                </li>

                            </ul>
                        </li>

                    }
                    <li class="nav-item" style="color: #c2c7d0!important;">
                        <a href="@Url.Action("LogOut", "Account")" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i>
                            <p>
                                Log Out
                            </p>
                        </a>
                    </li>



                </ul>
            </nav>

        </aside>


        <div class="content-wrapper" style="width:80%!important;margin-left:280px!important;">

            @RenderBody()




        </div>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>

    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.colVis.min.js"></script>

</body>
</html>

p1/Views/Shared/_LayoutLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Purchase</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
     @RenderBody()
    <script src="~/plugins/jquery/jquery.min.js"></script>

    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>
</body>
</html>